name: doremon

# The type of the application to build
type: 'python:3.10'

# The size of the persistent disk of the application (in MB)
disk: 1024

# Your app's configuration when it's exposed to the web.
web:
    commands:
        start: python app.py
web:
    locations:
        '/':
            passthru: true
            request_buffering:
                enabled: false
