"http://www.master-7rqtwti-frizvqik7y4qm.us.platformsh.site.":
    type: upstream
    upstream: "app:http"
"http://www.master-7rqtwti-frizvqik7y4qm.us.platformsh.site.":
    type: upstream
    upstream: "api:http"
"http://www.master-7rqtwti-frizvqik7y4qm.us.platformsh.site./ws":
    type: upstream
    upstream: "ws-app:http"
    cache:
        enabled: false
